export const REQUEST_CUSTOMER_ORDER = "REQUEST_CUSTOMER_ORDER";
export const SET_CUSTOMER_ORDER = "SET_CUSTOMER_ORDER";
export const ERROR_GET_CUSTOMER_ORDER = "ERROR_GET_CUSTOMER_ORDER";

export const REQUEST_UPDATE_CUSTOMER_ORDER = "REQUEST_UPDATE_CUSTOMER_ORDER";
export const SUCCESS_UPDATE_CUSTOMER_ORDER = "SUCCESS_UPDATE_CUSTOMER_ORDER";
export const ERROR_UPDATE_CUSTOMER_ORDER = "ERROR_UPDATE_CUSTOMER_ORDER";