export const REQUEST_MASTER_CATEGORY = "REQUEST_MASTER_CATEGORY";
export const SET_MASTER_CATEGORY = "SET_MASTER_CATEGORY";
export const ERROR_GET_MASTER_CATEGORY = "ERROR_GET_MASTER_CATEGORY";

export const REQUEST_CREATE_MASTER_CATEGORY = "REQUEST_CREATE_MASTER_CATEGORY";
export const SUCCESS_CREATE_MASTER_CATEGORY = "SUCCESS_CREATE_MASTER_CATEGORY";
export const ERROR_CREATE_MASTER_CATEGORY = "ERROR_CREATE_MASTER_CATEGORY";

export const REQUEST_UPDATE_MASTER_CATEGORY = "REQUEST_UPDATE_MASTER_CATEGORY";
export const SUCCESS_UPDATE_MASTER_CATEGORY = "SUCCESS_UPDATE_MASTER_CATEGORY";
export const ERROR_UPDATE_MASTER_CATEGORY = "ERROR_UPDATE_MASTER_CATEGORY";


export const SET_MESSAGE_MASTER_CATEGORY = "SET_MESSAGE_MASTER_CATEGORY";